# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use
      - name: Install pandoc
        run: echo "# Test" | pandoc -t html
      - name: Install dependencies
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("bbolker/bbmle")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
