# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
# https://github.com/marketplace/actions/ci-skip-action
on:
  push:
    branches:
      - main
      - master
      - ip_devel
      - documentation-action
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    if: ${{(!contains(github.event.head_commit.message, '[skip ci]')) || contains(github.event.head_commit.message, '[rebuild site]')}}

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use
      - name: Install pandoc
        run: echo "# Test" | pandoc -t html
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("bbolker/bbmle")
          install.packages('tinytex')
          tinytex::install_tinytex()
          tinytex::tlmgr_install("koma-script") # for scrtime.sty
          tinytex::tlmgr_install("amscls")      # for amsthm.sty
          tinytex::tlmgr_install(c("multirow","colortbl","siunitx","setspace"))
          tinytex::tlmgr_install(c("lineno","fancyhdr","ulem","caption"))
          tinytex::tlmgr_install("babel-english")
          tinytex::tlmgr_install("pgf") # tikz
          tinytex::tlmgr_install(c("placeins","lastpage","cleveref","listings"))
        shell: Rscript {0}
      - name: Check
        if: "! contains(github.event.head_commit.message, '[skip ci]')"
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Rebuild site #only works if R CMD check did not fail, if it was requested
        if: "contains(github.event.head_commit.message, '[rebuild site]')"
        run: |
          remotes::install_github("HenrikBengtsson/pkgdown.extras")
          pkgdown.extras::build_site(preview=FALSE)
        shell: Rscript{0}
      - name: Commit site
        if: "contains(github.event.head_commit.message, '[rebuild site]')"
        run: |
          git config --global user.name 'pkgdown-bot'
          git config --global user.email 'pkgdown-bot@users.noreply.github.com'
          git commit -am "Site rebuild [skip ci]"
          git push
