# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
# https://github.com/marketplace/actions/ci-skip-action
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: mstachniuk/ci-skip@v1
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use
      - name: Install pandoc
        if: ${{ env.CI_SKIP == 'false' }}
        run: echo "# Test" | pandoc -t html
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        if: ${{ env.CI_SKIP == 'false' }}
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("bbolker/bbmle")
          install.packages('tinytex')
          tinytex::install_tinytex()
          tinytex::tlmgr_install("koma-script") # for scrtime.sty
          tinytex::tlmgr_install("amscls")      # for amsthm.sty
          tinytex::tlmgr_install("multirow")
          tinytex::tlmgr_install("colortbl")
          tinytex::tlmgr_install("siunitx")
          tinytex::tlmgr_install("setspace")
          tinytex::tlmgr_install("lineno")
          tinytex::tlmgr_install("fancyhdr")
          tinytex::tlmgr_install("ulem")
          tinytex::tlmgr_install("caption")
          tinytex::tlmgr_install("babel-english")
          tinytex::tlmgr_install("pgf") # tikz
          tinytex::tlmgr_install("placeins")
          tinytex::tlmgr_install("lastpage")
          tinytex::tlmgr_install("cleveref")
          tinytex::tlmgr_install("listings")
        shell: Rscript {0}
      - name: Check
        if: ${{ env.CI_SKIP == 'false' }}
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
